### PR TITLE
CVE auth pop ups

### PR DESCRIPTION
**Pull request by chekl**
It is the visual appearance of login and registration pop-ups without auth logic.

### CODE REVIEW

**Comment by liubomyr123** [comment]
Same, try to use framer motion library - it is easy to use:
https://codesandbox.io/s/framer-motion-tutorial-forked-s6tftw?file=/src/App.js

**Comment by liubomyr123** [comment]
Looks cool!

**Comment by liubomyr123** [comment]
But on mozilla firefox it works incorrect. Check please. Maybe we can just center it on the screen.
https://drive.google.com/file/d/10-nooknWwcL0SAqPMYoSrc7ryjQ6XQMC/view?usp=sharing

**Comment by chekl** [comment]
> But on mozilla firefox it works incorrect. Check please. Maybe we can just center it on the screen. https://drive.google.com/file/d/10-nooknWwcL0SAqPMYoSrc7ryjQ6XQMC/view?usp=sharing

this video about old version of random present, not about popups

**Comment by liubomyr123** [comment]
> > But on mozilla firefox it works incorrect. Check please. Maybe we can just center it on the screen. https://drive.google.com/file/d/10-nooknWwcL0SAqPMYoSrc7ryjQ6XQMC/view?usp=sharing
> 
> this video about old version of random present, not about popups

yep, sorry, my bad. But u found the bug!
Here is the new bug of modal. I think it is better to open our modal only if it fully closed and vice versa - only if modal was opened fully - user can close it.
https://drive.google.com/file/d/1NG3Nh2YxjpVkPihTE4IABDd8jRA5oo3Y/view?usp=sharing

**Comment by liubomyr123** [comment]
Looks great, please resolve conflicts.

**Pull request merged**
